name: .NET Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        
    - name: Configure NuGet
      run: |
        cp nuget.config.template nuget.config
        sed -i 's/USERNAME_PLACEHOLDER/${{ secrets.NUGET_USERNAME }}/' nuget.config
        sed -i 's/PASSWORD_PLACEHOLDER/${{ secrets.NUGET_PAT }}/' nuget.config

    - name: Restore dependencies
      run: dotnet restore --configfile nuget.config

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      continue-on-error: true 
      run: |
        mkdir -p TestResults
        dotnet test --no-build --configuration Release --logger "trx;LogFileName=TestResults/test_results.trx"
      
    - name: List TestResults Directory
      if: always() 
      run: ls -la TestResults
      
    - name: Convert TRX to JUnit
      if: always() 
      run: |
        dotnet tool install -g trx2junit
        trx2junit TestResults/test_results.trx
        mkdir -p junit-reports
        mv TestResults/test_results.junit.xml junit-reports/test_results.xml

    - name: Upload JUnit Test Report
      if: always() 
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: junit-reports/test_results.xml
