name: .NET Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        
    - name: Configure NuGet
      run: |
        copy nuget.config.template nuget.config
        (Get-Content nuget.config -Raw) -replace 'USERNAME_PLACEHOLDER', "${{ secrets.NUGET_USERNAME }}" | Set-Content nuget.config -Force
        (Get-Content nuget.config -Raw) -replace 'PASSWORD_PLACEHOLDER', "${{ secrets.NUGET_PAT }}" | Set-Content nuget.config -Force

    - name: Restore dependencies
      run: dotnet restore --configfile nuget.config

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      continue-on-error: true
      run: |
        mkdir C:\Temp\TestResults
        dotnet test VontobelDemo.csproj --no-build --configuration Release --logger "trx;LogFileName=C:\Temp\TestResults\test_results.trx"
      
    - name: List TestResults Directory
      if: always()
      run: dir C:\Temp\TestResults
      
    - name: Convert TRX to JUnit
      if: always()
      run: |
        dotnet tool install -g trx2junit
        trx2junit C:\Temp\TestResults\test_results.trx
        mkdir junit-reports
        move C:\Temp\TestResults\test_results.junit.xml junit-reports\test_results.xml

    - name: Upload JUnit Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: junit-reports/test_results.xml
